PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX nct: <http://n2t.net/ark:/39333/ncg/type#>
PREFIX ncv: <http://n2t.net/ark:/39333/ncg/vocab#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# creeks in Orange County
SELECT ?uri ?name WHERE {

}
